import Table from "react-bootstrap/Table";
import { useState } from "react";
/* 
I want the table to be dynamically generated by inputs
from the user. 
*/

function TeamStatsTable() {
    

  return (
    <Table striped bordered hover variant="dark">
      <thead>
        <tr>
          <th>Name</th>
          <th>Health</th>
          <th>Attack</th>
          <th>Speed</th>
        </tr>
      </thead>
      <tbody>
        {players.map((player) => (
          <tr key={player.id}>
            <td>{player.name}</td>
            <td>{player.health}</td>
            <td>{player.attack}</td>
            <td>{player.speed}</td>
          </tr>
        ))};
      </tbody>
    </Table>
  );
}

export default TeamStatsTable;
